import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { resolveOpencodeTemplateSource } from "../src/core/framework-paths.js";
import { parseSimpleYaml } from "../src/core/yaml.js";

const scriptPath = fileURLToPath(import.meta.url);
const repoRoot = path.resolve(path.dirname(scriptPath), "..");
const marionettistBin = path.join(repoRoot, "bin", "marionettist.js");
const tempBase = process.env.HARNESS_SMOKE_TMP || os.tmpdir();
const ordinaryOpencodeProject = path.join(tempBase, `harness-self-smoke-opencode-${process.pid}`);
const ordinaryFullOpencodeProject = path.join(tempBase, `harness-self-smoke-opencode-full-${process.pid}`);
const standardOpencodeCommands = [
  "marionettist-context.md",
  "marionettist-status.md",
  "marionettist-continue.md"
];
const advancedOnlyOpencodeCommands = [
  "marionettist-feature.md",
  "marionettist-bugfix.md",
  "marionettist-refactor.md"
];
const selfOpencodeFiles = [
  "opencode.jsonc",
  ".opencode/README.md",
  ".opencode/commands/marionettist-self-init.md",
  ".opencode/commands/marionettist-self-review.md",
  ".opencode/commands/marionettist-self-test.md",
  ".opencode/agents/marionettist-framework-planner.md",
  ".opencode/agents/marionettist-framework-reviewer.md"
];
const mirrorChecks = [
  {
    sourceRelative: "commands/marionettist-feature.md",
    target: ".opencode/commands/marionettist-feature.md"
  },
  {
    sourceRelative: "commands/marionettist-incident.md",
    target: ".opencode/commands/marionettist-incident.md"
  },
  {
    sourceRelative: "agents/validators/generic-fallback.md",
    target: ".opencode/agents/validators/generic-fallback.md"
  }
];
try {
  await exec(process.execPath, [path.join(repoRoot, "scripts", "build-opencode-distribution.mjs"), "--check"], repoRoot);
  const expectedMirrorFiles = await getExpectedMirrorFiles();
  const initOutput = await harness("self", "init");
  assertIncludes(initOutput, "mode: dry-run");
  assertIncludes(initOutput, ".marionettist/self/README.md");
  assertIncludes(initOutput, "note: use --apply");

  const beforeRelevantOpencode = await readExistingFiles([...selfOpencodeFiles, ...expectedMirrorFiles]);
  const beforeTemplateAgents = await fs.readFile(path.join(repoRoot, "templates", "AGENTS.md"), "utf8");
  const beforeTemplateOpencodePathway = await snapshotDirectory(path.join(repoRoot, "templates", "pathways", "opencode"));
  const beforeSkills = await snapshotDirectory(path.join(repoRoot, "skills"));

  const selfOpencodeDryRun = await harness("self", "init", "--with-opencode");
  assertIncludes(selfOpencodeDryRun, "mode: dry-run");
  assertIncludes(selfOpencodeDryRun, ".opencode/agents/marionettist-framework-planner.md");
  assertIncludes(selfOpencodeDryRun, ".opencode/commands/marionettist-self-init.md");
  assertIncludes(selfOpencodeDryRun, ".opencode/agents/marionettist-builder.md");
  assertIncludes(selfOpencodeDryRun, ".opencode/agents/marionettist-planner.md");
  assertIncludes(selfOpencodeDryRun, ".opencode/commands/marionettist-feature.md");
  assertSameFileSnapshot(beforeRelevantOpencode, await readExistingFiles([...selfOpencodeFiles, ...expectedMirrorFiles]), "self init --with-opencode dry-run must not write files");

  const selfOpencodeApply = await harness("self", "init", "--apply", "--with-opencode");
  assertIncludes(selfOpencodeApply, "mode: write");
  assertIncludes(selfOpencodeApply, ".opencode/README.md");
  assertIncludes(selfOpencodeApply, ".opencode/agents/marionettist-builder.md");
  assertIncludes(selfOpencodeApply, ".opencode/commands/marionettist-feature.md");
  for (const relative of [...selfOpencodeFiles, ...expectedMirrorFiles]) {
    assert(await pathExists(path.join(repoRoot, relative)), `${relative} must be generated by self init --apply --with-opencode`);
  }
  assert(await pathExists(path.join(repoRoot, ".marionettist", "model-profiles.yml")), "self init --apply --with-opencode must ensure .marionettist/model-profiles.yml");
  assert(await pathExists(path.join(repoRoot, ".marionettist", "self", "README.md")), "self init --apply --with-opencode must ensure .marionettist/self/README.md");
  const gitignoreContent = await fs.readFile(path.join(repoRoot, ".gitignore"), "utf8");
  assertIncludes(gitignoreContent, ".marionettist-self/");

  for (const check of mirrorChecks) {
    const sourcePath = await resolvedTemplateOpencodePath(check.sourceRelative);
    assert((await readRelative(check.target)) === (await readRelative(sourcePath)), `${check.target} must exactly mirror ${sourcePath}`);
  }

  const selfOpencodeReadme = await readRelative(".opencode/README.md");
  assertIncludes(selfOpencodeReadme, "must not be edited directly");
  assertIncludes(selfOpencodeReadme, "Edit `templates/pathways/opencode/**` instead");

  const selfReviewer = await readRelative(".opencode/agents/marionettist-framework-reviewer.md");
  assertIncludes(selfReviewer, "model: deepseek/deepseek-v4-pro");

  const selfProfiles = parseSimpleYaml(await readRelative(".marionettist/model-profiles.yml"));
  const mirroredBuilder = await readRelative(".opencode/agents/marionettist-builder.md");
  assertIncludes(mirroredBuilder, `model: ${selfProfiles.profiles?.think?.default}`);
  assertExcludes(mirroredBuilder, "{{MODEL_PROFILE_");
  assertExcludes(mirroredBuilder, "{{OPENCODE_PERMISSION_");
  assertIncludes(mirroredBuilder, "permission:");
  assertIncludes(mirroredBuilder, "edit: allow");

  assert((await fs.readFile(path.join(repoRoot, "templates", "AGENTS.md"), "utf8")) === beforeTemplateAgents, "self OpenCode init must not modify templates/AGENTS.md");
  assertSameFileSnapshot(beforeTemplateOpencodePathway, await snapshotDirectory(path.join(repoRoot, "templates", "pathways", "opencode")), "self OpenCode init must not modify templates/pathways/opencode sources");
  assertSameFileSnapshot(beforeSkills, await snapshotDirectory(path.join(repoRoot, "skills")), "self OpenCode init must not modify skills");

  const doctorOutput = await harness("self", "doctor");
  assertIncludes(doctorOutput, "PASS  root AGENTS.md exists");
  assertIncludes(doctorOutput, "PASS  .marionettist/self/README.md exists");
  assertIncludes(doctorOutput, "PASS  .marionettist/model-profiles.yml exists");
  assertIncludes(doctorOutput, "PASS  .marionettist-self/ is ignored");
  assertIncludes(doctorOutput, "PASS  opencode.jsonc exists");
  assertIncludes(doctorOutput, "PASS  .opencode/commands/marionettist-self-test.md exists");
  assertIncludes(doctorOutput, "PASS  .opencode/agents/marionettist-framework-reviewer.md exists");
  assertIncludes(doctorOutput, `PASS  .opencode/agents/marionettist-planner.md matches ${await resolvedTemplateOpencodePath("agents/marionettist-planner.md")}`);
  assertIncludes(doctorOutput, `PASS  .opencode/commands/marionettist-feature.md matches ${await resolvedTemplateOpencodePath("commands/marionettist-feature.md")}`);

  await assertDoctorFailsForMissingSelfOpencodeFile();
  await assertDoctorFailsForUnresolvedPlaceholder();
  await assertDoctorFailsForUnresolvedPermissionPlaceholder();
  await assertMirrorDriftDetected();
  await assertMissingMirrorDetected();
  await assertOpencodeDistributionCheck();
  await assertLocalSelfModelProfilesPreservedAndRendered();
  await assertMirrorResyncFromTemplateSource();
  await assertOrdinaryOpencodeInitDoesNotInstallSelfFiles();
  await assertOrdinaryFullOpencodeInitRetainsAdvancedCommands();

  const templateAgents = await fs.readFile(path.join(repoRoot, "templates", "AGENTS.md"), "utf8");
  assertExcludes(templateAgents, "HARNESS_SELF_POLICY");
  assertExcludes(templateAgents, ".marionettist-self");
  assertSameFileSnapshot(beforeTemplateOpencodePathway, await snapshotDirectory(path.join(repoRoot, "templates", "pathways", "opencode")), "self smoke must restore templates/pathways/opencode sources after resync test");

  const testOutput = await harness("self", "test");
  assertIncludes(testOutput, "Marionettist Self Test");
  assertIncludes(testOutput, "PASS  target-empty manifest exists");
  assertIncludes(testOutput, "PASS  target-existing-agents local AGENTS.md content preserved");
  assertIncludes(testOutput, "PASS  target-conflict-managed-block local content preserved");
  assertIncludes(testOutput, "PASS  target-conflict-managed-block sync dry-run preserves AGENTS.md");
  assertIncludes(testOutput, "PASS  target-old-manifest reports missing managed AGENTS.md");
  assertIncludes(testOutput, "PASS  templates/AGENTS.md remains free of self rules");
  assertIncludes(testOutput, "sandbox:");

  console.log("self-smoke: PASS");
} finally {
  await fs.rm(ordinaryOpencodeProject, { recursive: true, force: true });
  await fs.rm(ordinaryFullOpencodeProject, { recursive: true, force: true });
}

async function harness(...args) {
  return exec(process.execPath, [marionettistBin, ...args], repoRoot);
}

async function assertProjectDoctorBaseline(projectPath, label) {
  const result = await harnessAllowFailure("doctor", "--project", projectPath);
  assert(result.code === 0, `doctor must pass for ${label}`);
  assertIncludes(result.stdout, "PASS  AGENTS.md managed block found");
  return result.stdout;
}

async function exec(command, args, cwd) {
  return new Promise((resolve, reject) => {
    execFile(command, args, { cwd, encoding: "utf8" }, (error, stdout, stderr) => {
      if (error) {
        error.message = `${error.message}\nstdout:\n${stdout}\nstderr:\n${stderr}`;
        reject(error);
        return;
      }
      resolve(stdout);
    });
  });
}

async function harnessAllowFailure(...args) {
  return execAllowFailure(process.execPath, [marionettistBin, ...args], repoRoot);
}

async function execAllowFailure(command, args, cwd) {
  return new Promise((resolve) => {
    execFile(command, args, { cwd, encoding: "utf8" }, (error, stdout, stderr) => {
      resolve({ code: error?.code ?? 0, stdout, stderr });
    });
  });
}

async function assertDoctorFailsForMissingSelfOpencodeFile() {
  const relative = ".opencode/commands/marionettist-self-test.md";
  const absolute = path.join(repoRoot, relative);
  const backup = `${absolute}.self-smoke-bak`;
  await fs.rename(absolute, backup);
  try {
    const result = await harnessAllowFailure("self", "doctor");
    assert(result.code !== 0, "self doctor must fail when a required self OpenCode file is missing");
    assertIncludes(result.stdout, `FAIL  ${relative} missing`);
  } finally {
    await fs.rename(backup, absolute);
  }
}

async function assertMirrorDriftDetected() {
  const mirror = ".opencode/agents/marionettist-planner.md";
  const absolute = path.join(repoRoot, mirror);
  const original = await fs.readFile(absolute, "utf8");
  try {
    await fs.writeFile(absolute, `${original}\nDrifted locally.\n`, "utf8");
    const result = await harnessAllowFailure("self", "doctor");
    assert(result.code !== 0, "self doctor must fail when a mirror file drifts");
    assertIncludes(result.stdout, `${mirror} drifted from ${await resolvedTemplateOpencodePath("agents/marionettist-planner.md")}`);
    assertIncludes(result.stdout, "Edit that template source, then rerun marionettist self init --apply --with-opencode.");
  } finally {
    await fs.writeFile(absolute, original, "utf8");
  }
}

async function assertMissingMirrorDetected() {
  const mirror = ".opencode/commands/marionettist-feature.md";
  const absolute = path.join(repoRoot, mirror);
  const backup = `${absolute}.self-smoke-bak`;
  await fs.rename(absolute, backup);
  try {
    const result = await harnessAllowFailure("self", "doctor");
    assert(result.code !== 0, "self doctor must fail when a mirror file is missing");
    assertIncludes(result.stdout, `${mirror} missing; mirror drift from ${await resolvedTemplateOpencodePath("commands/marionettist-feature.md")}`);
    assertIncludes(result.stdout, "Edit that template source, then rerun marionettist self init --apply --with-opencode.");
  } finally {
    await fs.rename(backup, absolute);
  }
}

async function assertMirrorResyncFromTemplateSource() {
  const source = await resolvedTemplateOpencodePath("agents/marionettist-planner.md");
  const target = ".opencode/agents/marionettist-planner.md";
  const sourceAbsolute = path.join(repoRoot, source);
  const targetAbsolute = path.join(repoRoot, target);
  const originalSource = await fs.readFile(sourceAbsolute, "utf8");
  const modifiedSource = `${originalSource}\n<!-- self-smoke template resync -->\n`;
  try {
    await fs.writeFile(sourceAbsolute, modifiedSource, "utf8");
    const output = await harness("self", "init", "--apply", "--with-opencode");
    assertIncludes(output, target);
    assertIncludes(await fs.readFile(targetAbsolute, "utf8"), "<!-- self-smoke template resync -->");
  } finally {
    await fs.writeFile(sourceAbsolute, originalSource, "utf8");
    await harness("self", "init", "--apply", "--with-opencode");
    assertExcludes(await fs.readFile(targetAbsolute, "utf8"), "<!-- self-smoke template resync -->");
  }
}

async function assertLocalSelfModelProfilesPreservedAndRendered() {
  // Keep this as self-smoke evidence for self.js mirror rendering because the
  // bounded regression slice avoids exporting additional self-only helpers just
  // for unit tests. This exercises the real self init render path end-to-end.
  const profilesRelative = ".marionettist/model-profiles.yml";
  const builderRelative = ".opencode/agents/marionettist-builder.md";
  const profilesAbsolute = path.join(repoRoot, profilesRelative);
  const builderAbsolute = path.join(repoRoot, builderRelative);
  const originalProfiles = await fs.readFile(profilesAbsolute, "utf8");
  const originalBuilder = await fs.readFile(builderAbsolute, "utf8");
  const overriddenProfiles = originalProfiles.replace(
    /^    default: ".*"$/m,
    '    default: "self/smoke-think"'
  );
  try {
    await fs.writeFile(profilesAbsolute, overriddenProfiles, "utf8");
    const output = await harness("self", "init", "--apply", "--with-opencode");
    assertIncludes(output, "skip-project-local: .marionettist/model-profiles.yml");
    assert((await fs.readFile(profilesAbsolute, "utf8")) === overriddenProfiles, ".marionettist/model-profiles.yml local edits must be preserved by self init");
    assertIncludes(await fs.readFile(builderAbsolute, "utf8"), "model: self/smoke-think");
  } finally {
    await fs.writeFile(profilesAbsolute, originalProfiles, "utf8");
    await fs.writeFile(builderAbsolute, originalBuilder, "utf8");
    await harness("self", "init", "--apply", "--with-opencode");
  }
}

async function assertDoctorFailsForUnresolvedPlaceholder() {
  const relative = ".opencode/agents/marionettist-builder.md";
  const absolute = path.join(repoRoot, relative);
  const original = await fs.readFile(absolute, "utf8");
  try {
    await fs.writeFile(absolute, original.replace(/^model: .*$/m, "model: {{MODEL_PROFILE_THINK}}"), "utf8");
    const result = await harnessAllowFailure("self", "doctor");
    assert(result.code !== 0, "self doctor must fail when a mirror keeps unresolved placeholders");
    assertIncludes(result.stdout, `${relative} still contains unresolved MODEL_PROFILE placeholders`);
  } finally {
    await fs.writeFile(absolute, original, "utf8");
  }
}

async function assertDoctorFailsForUnresolvedPermissionPlaceholder() {
  const relative = ".opencode/agents/marionettist-builder.md";
  const absolute = path.join(repoRoot, relative);
  const original = await fs.readFile(absolute, "utf8");
  try {
    await fs.writeFile(absolute, original.replace(/^permission:\n(?:  .*\n)+?/m, "{{OPENCODE_PERMISSION_BLOCK_HARNESS_BUILDER}}\n"), "utf8");
    const result = await harnessAllowFailure("self", "doctor");
    assert(result.code !== 0, "self doctor must fail when a mirror keeps unresolved permission placeholders");
    assertIncludes(result.stdout, `${relative} still contains unresolved OPENCODE_PERMISSION placeholders`);
    assertIncludes(result.stdout, "Rerun marionettist self init --apply --with-opencode.");
  } finally {
    await fs.writeFile(absolute, original, "utf8");
  }
}

async function assertOrdinaryOpencodeInitDoesNotInstallSelfFiles() {
  await fs.rm(ordinaryOpencodeProject, { recursive: true, force: true });
  const output = await harness("init", "--project", ordinaryOpencodeProject, "--auto", "--with-opencode");
  assertIncludes(output, "new-managed: opencode.jsonc");
  assert(await pathExists(path.join(ordinaryOpencodeProject, "opencode.jsonc")), "ordinary init --with-opencode must still generate opencode.jsonc");
  assert(!(await pathExists(path.join(ordinaryOpencodeProject, ".opencode"))), "ordinary init package default must not create generated fallback assets");

  const config = await fs.readFile(path.join(ordinaryOpencodeProject, "marionettist.config.yaml"), "utf8");
  assertIncludes(config, 'pluginSource: "package"');

  const manifest = await readProjectManifest(ordinaryOpencodeProject);
  assert(manifest.opencodePluginSource === "package", "ordinary init package default must record package plugin source");
  assert(!manifest.managedFiles.some((file) => file.path.startsWith(".opencode/")), "ordinary init package default must not manage generated fallback assets");

  const projectConfig = await fs.readFile(path.join(ordinaryOpencodeProject, "opencode.jsonc"), "utf8");
  assertIncludes(projectConfig, '"plugin": ["marionettist-pathway-opencode"]');

  const syncOutput = await switchOrdinaryProjectToLocalFallback(ordinaryOpencodeProject);
  assertIncludes(syncOutput, "new-managed: .opencode/commands/marionettist.md");
  assertIncludes(syncOutput, "new-managed: .opencode/agents/marionettist-planner.md");
  assertIncludes(syncOutput, "update: opencode.jsonc");

  assert(await pathExists(path.join(ordinaryOpencodeProject, ".opencode", "agents", "marionettist-planner.md")), "ordinary local fallback must generate template agent files");
  assert(await pathExists(path.join(ordinaryOpencodeProject, ".opencode", "commands", "marionettist.md")), "ordinary local fallback must install the minimal builder command");
  const ordinaryBuilder = await fs.readFile(path.join(ordinaryOpencodeProject, ".opencode", "agents", "marionettist-builder.md"), "utf8");
  assertIncludes(ordinaryBuilder, "model: openai/gpt-5.5");
  assertExcludes(ordinaryBuilder, "{{MODEL_PROFILE_THINK}}");
  assert(!(await pathExists(path.join(ordinaryOpencodeProject, ".opencode", "commands", "marionettist-feature.md"))), "ordinary local fallback minimal default must not install advanced feature command files");
  assert(!(await pathExists(path.join(ordinaryOpencodeProject, ".opencode", "commands", "marionettist-self-init.md"))), "ordinary init must not install self command files");
  assert(!(await pathExists(path.join(ordinaryOpencodeProject, ".opencode", "commands", "marionettist-self-review.md"))), "ordinary init must not install self review command files");
  assert(!(await pathExists(path.join(ordinaryOpencodeProject, ".opencode", "commands", "marionettist-self-test.md"))), "ordinary init must not install self test command files");
  assert(!(await pathExists(path.join(ordinaryOpencodeProject, ".opencode", "agents", "marionettist-framework-planner.md"))), "ordinary init must not install self planner agent files");
  assert(!(await pathExists(path.join(ordinaryOpencodeProject, ".opencode", "agents", "marionettist-framework-reviewer.md"))), "ordinary init must not install self reviewer agent files");

  const localFallbackProjectConfig = await fs.readFile(path.join(ordinaryOpencodeProject, "opencode.jsonc"), "utf8");
  assertIncludes(localFallbackProjectConfig, '"plugin": ["./.opencode/plugin/opencode-tasks.js"]');
}

async function assertOrdinaryFullOpencodeInitRetainsAdvancedCommands() {
  await fs.rm(ordinaryFullOpencodeProject, { recursive: true, force: true });
  const output = await harness("init", "--project", ordinaryFullOpencodeProject, "--auto", "--with-opencode", "--opencode-command-surface", "full");
  assertIncludes(output, "new-managed: opencode.jsonc");
  assert(!(await pathExists(path.join(ordinaryFullOpencodeProject, ".opencode"))), "ordinary full package default must not create generated fallback assets");

  const syncOutput = await switchOrdinaryProjectToLocalFallback(ordinaryFullOpencodeProject, { commandSurface: "full" });
  assertIncludes(syncOutput, "new-managed: .opencode/commands/marionettist-feature.md");
  for (const command of [...standardOpencodeCommands, ...advancedOnlyOpencodeCommands]) {
    assert(await pathExists(path.join(ordinaryFullOpencodeProject, ".opencode", "commands", command)), `ordinary full init must install ${command}`);
  }
  assert(!(await pathExists(path.join(ordinaryFullOpencodeProject, ".opencode", "commands", "marionettist-self-init.md"))), "ordinary full local fallback must not install self command files");

  const doctorOutput = await assertProjectDoctorBaseline(ordinaryFullOpencodeProject, "ordinary full OpenCode local fallback install");
  assertIncludes(doctorOutput, "PASS  OpenCode command surface [advanced] required normal commands present");
  assertIncludes(doctorOutput, "PASS  OpenCode command surface [advanced] standard helper commands present");
  assertIncludes(doctorOutput, "PASS  OpenCode command surface [advanced] advanced commands present");
}

async function assertOpencodeDistributionCheck() {
  const script = path.join(repoRoot, "scripts", "build-opencode-distribution.mjs");
  await exec(process.execPath, [script, "--check"], repoRoot);
}

async function getExpectedMirrorFiles() {
  const relativeFiles = [];
  for (const root of ["agents", "commands"]) {
    await collectRelativeFiles(path.join(repoRoot, "templates", "pathways", "opencode", root), `.opencode/${root}`, relativeFiles);
  }
  relativeFiles.sort();
  return relativeFiles;
}

async function collectRelativeFiles(sourceDirectory, targetPrefix, relativeFiles) {
  const children = await fs.readdir(sourceDirectory, { withFileTypes: true });
  for (const child of children) {
    const childSource = path.join(sourceDirectory, child.name);
    const childTarget = `${targetPrefix}/${child.name}`;
    if (child.isDirectory()) {
      await collectRelativeFiles(childSource, childTarget, relativeFiles);
      continue;
    }
    if (child.isFile()) {
      relativeFiles.push(childTarget);
    }
  }
}

async function readExistingFiles(relativeFiles) {
  const entries = [];
  for (const relative of relativeFiles) {
    const absolute = path.join(repoRoot, relative);
    entries.push([relative, await pathExists(absolute) ? await fs.readFile(absolute, "utf8") : null]);
  }
  return entries;
}

async function readRelative(relative) {
  return fs.readFile(path.join(repoRoot, relative), "utf8");
}

async function resolvedTemplateOpencodePath(sourceRelative) {
  const resolvedSource = await resolveOpencodeTemplateSource(sourceRelative);
  assert(resolvedSource, `expected resolved template source for ${sourceRelative}`);
  return resolvedSource.sourceRelative;
}

async function snapshotDirectory(directoryPath) {
  const entries = [];
  await collectFiles(directoryPath, "", entries);
  return entries;
}

async function collectFiles(directoryPath, relativePrefix, entries) {
  const children = await fs.readdir(directoryPath, { withFileTypes: true });
  for (const child of children) {
    const childAbsolute = path.join(directoryPath, child.name);
    const childRelative = relativePrefix ? `${relativePrefix}/${child.name}` : child.name;
    if (child.isDirectory()) {
      await collectFiles(childAbsolute, childRelative, entries);
      continue;
    }
    entries.push([childRelative, await fs.readFile(childAbsolute, "utf8")]);
  }
  entries.sort(([left], [right]) => left.localeCompare(right));
  return entries;
}

async function pathExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function readProjectManifest(projectPath) {
  return JSON.parse(await fs.readFile(path.join(projectPath, ".marionettist", "manifest.json"), "utf8"));
}

async function switchOrdinaryProjectToLocalFallback(projectPath, { commandSurface = "minimal" } = {}) {
  const configPath = path.join(projectPath, "marionettist.config.yaml");
  let config = await fs.readFile(configPath, "utf8");
  config = config.replace('pluginSource: "package"', 'pluginSource: "local"');
  await fs.writeFile(configPath, config, "utf8");

  const syncArgs = ["sync", "--project", projectPath, "--with-opencode"];
  if (commandSurface === "full") {
    syncArgs.push("--opencode-command-surface", "full");
  }

  return harness(...syncArgs);
}

function assert(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}

function assertIncludes(content, expected) {
  assert(content.includes(expected), `Expected output to include: ${expected}\nActual output:\n${content}`);
}

function assertSameFileSnapshot(left, right, message) {
  assert(JSON.stringify(left) === JSON.stringify(right), message);
}

function assertExcludes(content, unexpected) {
  assert(!content.includes(unexpected), `Expected output to exclude: ${unexpected}\nActual output:\n${content}`);
}
